service: nodeless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"  # All buckets

functions:
  index:
    handler: index.handle
    environment:
      bucket: gabs-serverless-test
    events:
      - s3:
          bucket: gabs-serverless-test
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: gabs-serverless-test
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
